//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCreation
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public long MobileNo { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public string Reporting_Person { get; set; }
    }
}
